# For more information see: https://github.com/jenkey2011/vuepress-deploy/blob/master/README.zh-CN.md

name: Publish LUCKY Document

on:
  push:
    branches: 
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile #Use yarn.lock to install dependencies
      - name: Build
        run: yarn docs:build
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          # Set a SSH private key from repository secret value for pushing to the remote branch.
          #deploy_key: ${{ secrets.ACCESS_TOKEN }} # optional
          # Set a generated GITHUB_TOKEN for pushing to the remote branch.
          github_token: ${{ secrets.GITHUB_TOKEN }} # optional
          # Set a personal access token for pushing to the remote branch.
          #personal_token: # optional
          # Set a target branch for deployment.
          publish_branch: master # optional, default is gh-pages
          # Set an input directory for deployment.
          publish_dir: ./docs/.vuepress/dist # optional, default is public
          # Set an external repository (owner/repo).
          # external_repository: # optional
          # If empty commits should be made to the publication branch
          allow_empty_commit: false # optional, default is false
          # If existing files in the publish branch should be not removed before deploying
          keep_files: false # optional, default is false
          # Keep only the latest commit on a GitHub Pages branch
          force_orphan: true # optional, default is false
          # Set custom domain
          #cname: # optional
