# For more information see: https://github.com/jenkey2011/vuepress-deploy/blob/master/README.zh-CN.md

name: Publish LUCKY Document

on:
  push:
    branches: 
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vuepress deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn --frozen-lockfile && yarn docs:build #Use yarn.lock to install dependencies
          BUILD_DIR: docs/.vuepress/dist/
